
SELECT p.PRODUCT_CODE,SUM(o.SALES_AMOUNT * p.PRICE) as SALES
FROM PRODUCT as p 
     JOIN OFFLINE_SALE as o
     ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES desc,p.PRODUCT_CODE asc;



