-- 코드를 입력하세요
SELECT p.PRODUCT_CODE,SUM(p.PRICE*o.SALES_AMOUNT) as 'SALES'
FROM PRODUCT as p 
     JOIN OFFLINE_SALE as o
     ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES desc,p.PRODUCT_CODE asc;



# SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS 'SALES'
# FROM PRODUCT AS P
# INNER JOIN OFFLINE_SALE AS O ON P.PRODUCT_ID = O.PRODUCT_ID
# GROUP BY P.PRODUCT_CODE
# ORDER BY `SALES` DESC, P.PRODUCT_CODE ASC;