select b.BOOK_ID,a.AUTHOR_NAME,DATE_FORMAT(b.PUBLISHED_DATE,"%Y-%m-%d") as PUBLISHED_DATE

FROM BOOK as b
     JOIN AUTHOR as a
     ON b.AUTHOR_ID = a.AUTHOR_ID
     
WHERE b.CATEGORY = "경제"
ORDER BY b.PUBLISHED_DATE asc;

# select AUTHOR_ID
# FROM BOOK
# WHERE CATEGORY = "경제"